var GAME_LEVELS = [
  ["y         y y          y       y                                 y       y      ",
   "y          y          y y     y                      y y          y     y       ",
   " y        y y       yy   yyyyy y                    x y          y yy  y        ",
   "  y      y   yy    y           y                    xxxxxx       y   yy         ",
   "   yy   y      yyyy            y                         x       y              ",
   "     yyy                                    o o          x       y              ",
   "                                                         x                      ",
   "                                         xxxxxxxxx       x                      ",
   "                                        x                x                      ",
   "                                 xxxxxxx                 x                      ",
   "  xx             o              x                     y yx                  xx  ",
   "  x            o   o           x                       y x              o    x  ",
   "  x           o     o         x               xxxxxxxxxxxx                   x  ",
   "  x                          x           xxxxx                         xxx   x  ",
   "  x          x              x                                      xxx       x  ",
   "  x         xx    x        x   y y                  o o          xxx     y y x  ",
   "  x  @     xxx    xx      x     y                                         y  x  ",
   "  xxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxx      xxxxxxxxx  ",
   "             xxxxxx                            x   xxxxx   x  xxxxxxxx          ",
   "                                               x           x                    ",
   "                                               x!!!!!!!!!!!x                    ",
   "                                               xxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                           xxxxxxxxxxxxxxx                                                    ",
   "                                         xx               xx                                                  ",
   "                                        x                   x                                                 ",
   "                                       x                     x                                                ",
   "                                       x                     x                                                ",
   "                                       x        sssss        x                                                ",
   "                                       x        xxxxx        x                                                ",
   "                                       x                     x                                                ",
   "                                       x    xx         xx    x                                                ",
   "                                       x                     x                                                ",
   "                                        x        x x        x                                                 ",
   "                                         xx     x^^^x     xx                                                  ",
   "         o                                 xxxxxxxxxxxxxxx                                                    ",
   "       x   x                                                                                                  ",
   "x      x o x                                                                                                  ",
   "x @   xx   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxx o xxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxx",
   "       x             x!!!!!!!!!!!!!!!!!!!!!x                                           x!!!x                 x",
   "       x             xxxxxxxxxx!xxxxxx!xxxxx      xxxxxxxxx                             x!x            yyy   x",
   "       x                      xvx    xvx        xxx       xxx                           xvx           y   y  x",
   "       x                                            o   o                                             y o y  x",
   "       x                          oo                                                           xxxxxxxxxxxxxxx",
   "       x                                        xxx       xxx                                 x               ",
   "       x                                          xxxxxxxxx               xxxxxxxxxxxx       x                ",
   "       x                xxxxxxxxxxxxxxxxxxxxx                            x                  x                 ",
   "       xxx             x                                          xxxxxxx                  x                  ",
   "         xxxxxxxxxx                                           xxxx                        x                   ",
   "                  x      o           xxxxxxx      xxxxxxxxxxxxx                          x                    ",
   "                  x                 x       x     x                     xxxxxxxxxxxxxxxxx                     ",
   "                  xx               x         x     x               xxxxx               x                      ",
   "                  xxxxxx!!!xxxxxxxx           x     x             x    x               x                      ",
   "                       xxxxx                   x     x           xxxxxx       o  o     x                      ",
   "          xxxxxxxxxx                          x     x                                  x                      ",
   "          x        x!!!!!!!!!!!!!!!!!!!!!!!!!x     x                         xxxxxx    x                      ",
   "          x        xxxxxxxxxxxxxxxxxxxxxxxxxx     x           xxxxxxxxxxxxx          xxx                      ",
   "          x        x                             x           x          x!!!!!!!!!!!!!!x                      ",
   "          x                                                 x           xxxxxxxxxxxxxxxx                      ",
   "          x  x x               o   o   o   o            o  x                                                  ",
   "          x xpppx  x                                      x                                                   ",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                   "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "x         x                                                  x                   x       x      x             ",
   "x         x                                                  x                   x       x      x             ",
   "x         x                                                  x                   x       x      x             ",
   "x         x               o  o                               x                   x       x      x             ",
   "x         x                                                  x                   x       x      x             ",
   "x         x            xxxxxxxxxx                            x           yyy     x       x      x             ",
   "x  @ w    x                                                  x          y   y    x       x      x             ",
   "xxxxxxx   x       xx                xx   xxxxxxxx            x  # #     y o y   x        x      x             ",
   "      x   x        x!!!!!!!!!!!!!!!!x                        x  ###xxxxxxxxxxxxx         x      x             ",
   "      x   x         xxxxxxxxxxxxxxxx                xxx      x  # #                      x      x             ",
   "      x   x                                   o              x  ###                      x       x            ",
   "      x   x                                                  x  # #                      x        x           ",
   "      x   x                                 xxxxxx           x  ###                      x         x          ",
   "      x   x                                                  x  # #                      x          x         ",
   "      x   x                             xx!!!!!!!!!!xx       x  ###                      x           x        ",
   "      x   x                               xxxxxxxxxx         x  # #                      x            x       ",
   "      x   x                     xxxxx                        x  ###                      x             x      ",
   "      x   x                 o                                x  # #                      x              x     ",
   "      x   x                                                  x  ###                      x               x    ",
   "      xgggx                xxxx                              x  # #                     xgggggggggggggggggx   ",
   "      xggggx                        x               x                            x x   xgggggggggggggggggggx  ",
   "      xggggggx     n               x!!!!!!!!!!!!!!!!!x           o              xuuux xgggggggggggggggggggggx ",
   "      xgggggggxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxgggggggg  gggggggggggggx",
   "      xggggggggggggggggx!!!xgggggggggggggggggggggggggggggggggggggggggggggx!!!xgggggggggggggg  gggggggggggggggx",
   "      xgggggggggggggggggxvxgggggggggggg ggggggggggggggggggggggggg ggggggggxvxggggggggggggggggggggggggggggggggx",
   "      xggggggggggggggggggggggggggggggggggggfgoogfgggggggggggggggggggggggggggggggggggggggggggggggggggxxxxxxxxxx",
   "      xggggggggggfggggggggggggggfggggggggggggggggggggggg ggggggfgggggggggggg gggogggggggggggggggggggxggggggggx",
   "       xggggggggggggggggggggggggogggggxxxxxxxxxxxxxxxgggg ggggggggggggggggggggggggggggggggfgggggggggxggggfgggx",
   "        xgggggggggggggggggggggggggggggggggggggggggggggggggggxxxxxxgggggggggggggggggggggggggggggggggggggggggggx",
   "         xgggggggg  gggggggggxxxxxxgggggggggggggggggggggggggggggggg ggggggggggggxgggggggggg gggggggggggggggggx",
   "          xgggggggggggggggggggggggggggggxxgggggggg  ggggggggggggg ggggggggggggggxxggggggggggggggggggggggxgxggx",
   "           xggggggggggxggggggggggggggggxxxxxggggggggggxxgggggggggggggggggggggggxxxggggggggggggggggggxggxtttxgx",
   "            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxggxxxxxxxxxxxxxgggxxxxxxxxxxxxxxxxxxxxx",
   "                                                                      xgggggfgggggfgggggx                     ",
   "                                                                       xgggggogogogggggx                      ",
   "                                                                        xxxxxxxxxxxxxxx                       ",
   "                                                                                                              "],
  ["                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "   y           y    yyy       y       y          y     y     y   y   yy           y     ",
   "    y         y    y   y      y       y          y    y y    y   y   y y          y     ",
   "     y       y    y     y     y       y          y    y y    y   y   y  y         y     ",
   "      y     y    y       y    y       y          y    y y    y   y   y   y        y     ",
   "       y   y    y         y   y       y          y    y y    y   y   y    y       y     ",
   "        y y     y         y   y       y          y    y y    y   y   y     y      y     ",
   "         y      y         y   y       y          y    y y    y   y   y      y     y     ",
   "         y      y         y   y       y          y    y y    y   y   y       y    y     ",
   "         y       y       y    y       y          y    y y    y   y   y        y   y     ",
   "         y        y     y      y     y           y   y   y   y   y   y         y  y     ",
   "         y         y   y        y   y            y  y     y  y   y   y          y y     ",
   "         y          yyy          yyy              yy       yy    y   y           yy     ",
   "                                                                                        ",
   "    @                                                                                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                        ",
   "                                                                                        "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
